name: Deploy to Ukraine.com.ua

on:
  push:
    branches:
      - main      # запускати деплой при кожному push у гілку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: CI=false npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v3.1.0
        with:
          ftp-server: ftp://ftp.filada.com.ua/filada.com.ua/www
          ftp-username: ${{ secrets.FTP_LOGIN }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          git-ftp-args: --insecure
